### ISSUE TITLE
[CS:GO] No Steam not Work

### ISSUE THREAD

**Issue by BlackYuzia** [Exle/Voice-Over#2]
@Exle данный плагин не работает для Пиратов. 

> хотя, вроде, в обсуждении на HLMOD говорилось об обратном :c 

Если нет возможности поддерживать работоспособность для пиратов, так и укажите в описании.
Если же это возможно, поправьте. **Спасибо**

**Comment by Exle** [comment]
No steam - no support, как было раньше на HLmod.
